name: AI Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}
          submodules: false
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_LIGHT_MODEL: ${{ vars.OPENAI_LIGHT_MODEL }}
          OPENAI_HEAVY_MODEL: ${{ vars.OPENAI_HEAVY_MODEL }}
        with:
          debug: true
          review_comment_lgtm: false
          openai_heavy_model: gpt-4
          openai_light_model:  gpt-35-turbo-16k
          openai_base_url: https://${{ secrets.OPENAI_AZURE_ENDPOINT }}.openai.azure.com/
          path_filters: |
            !dist/**
            !**/*.lock
